### ISSUE TITLE
[QA] Asset list in "From" section is incomplete for some networks on deploy-preview-2985

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#3138]
## Describe the current behavior in detail
Reproducible on [Netlify preview-2985](https://deploy-preview-2985--wormhole-connect-mainnet.netlify.app/?config=N4KABGDGD2CWB2BxAppA1tAggB1gaWQE8AuMAcgGFEBaAUQBEAZAMwBdGBDAMVoHUBNAI4AtAHIBnAAoA1AO4AhepjwVaZADTgwAJ2gBXVsnGkA2gFkOhDvABK%2BwwGVeASS4AVdWAB0P%2BrS6YAKqMbgD6NgDygW60DgC6IAC%2BQA%3D).
Balances are displayed correctly on https://wormhole-connect-mainnet.netlify.app/. 

Steps:
1. Select X Layer as source chain
2. Connect MetaMask wallet 
3. Open "From" section and check available assets

Actual result: Only OKB asset is displayed in the list, other assets are not displayed. 
Expected result: All available assets are displayed in the list. 

## Notes/ Attachments

![Screenshot 2025-01-06 at 09 29 24](https://github.com/user-attachments/assets/21af6e6b-8e50-46bf-814c-0e2d07759183)

**Comment by tsadovska** [comment]
Issue is also reproducible with:
* Mantle network, ticket https://github.com/wormhole-foundation/wormhole-connect/issues/3139
* Scroll network, ticket https://github.com/wormhole-foundation/wormhole-connect/issues/3141
* Sui network - only SUI token is listed:

![Screenshot 2025-01-06 at 13 38 56](https://github.com/user-attachments/assets/4c45d05d-337e-450b-bd3b-0e3028777287)

**Comment by tsadovska** [comment]
WGLMR asset (contract address, [0x944C5b67a03e6Cb93Ae1E4B70081f13b04CDB6Bd](https://arbiscan.io/address/0x944C5b67a03e6Cb93Ae1E4B70081f13b04CDB6Bd)) is displayed in the list only after contract address is entered. 

https://github.com/user-attachments/assets/d1c6f93c-10cf-412d-90e3-dc3d1344da8a

**Comment by artursapek** [comment]
yeah I actually did this on purpose but in hindsight this was a bad move. ideally we could just load all of the wallet's balances but we can't do that yet for EVM chains. I've reverted this behavior so we show all these wrapped tokens again.

**Comment by artursapek** [comment]
this should be fixed in that deploy preview

**Comment by tsadovska** [comment]
Rechecked the issue on [Netlify (preview 2985)](https://deploy-preview-2985--wormhole-connect-mainnet.netlify.app/?config=N4KABGDGD2CWB2BxAppA1tAggB1gaWQE8AuMAcgGFEBaAUQBEAZAMwBdGBDAMVoHUBNAI4AtAHIBnAAoA1AO4AhepjwVaZADTgwAJ2gBXVsnGkA2gFkOhDvABK%2BwwGVeASS4AVdWAB0P%2BrS6YAKqMbgD6NgDygW60DgC6IAC%2BQA%3D), issue still occurs.

* Ethereum, Solana, Arbitrum, Base, BSC, Optimism, Fantom, Polygon, Avalanche, Celo, Moonbeam,  Scroll, Mantle, Blast, X Layer, World Chain - only native tokens are displayed

![Screenshot 2025-01-08 at 10 30 51](https://github.com/user-attachments/assets/778252f3-1659-4ce0-b6fa-f56340b15fdb)


![Screenshot 2025-01-08 at 10 27 52](https://github.com/user-attachments/assets/8112a8cb-2b76-49c1-adf2-23f680e36f51)

* Sui, Aptos - no supported tokens found

![image](https://github.com/user-attachments/assets/1d1ec67e-9db4-4bfd-a957-f5d01cd580ea)

![image](https://github.com/user-attachments/assets/8f88485b-e6d3-4254-9d6e-9d2b7b8b52e6)


* Kaia - KLAY option is greyed out. Wrapped tokens are not displayed on wormhole-connect because of free RPC endpoint on Netlify deployments. Tokens are successfully loaded on Portal Bridge. Please see ticket https://github.com/wormhole-foundation/wormhole-connect/issues/2834. 

![Screenshot 2025-01-08 at 13 20 13](https://github.com/user-attachments/assets/161a4ca6-6918-4a2c-83e2-8da48528f88a)

**Comment by tsadovska** [comment]
Rechecked the issue on [Netlify (preview 2985)](https://deploy-preview-2985--wormhole-connect-mainnet.netlify.app/?config=N4KABGDGD2CWB2BxAppA1tAggB1gaWQE8AuMAcgGFEBaAUQBEAZAMwBdGBDAMVoHUBNAI4AtAHIBnAAoA1AO4AhepjwVaZADTgwAJ2gBXVsnGkA2gFkOhDvABK%2BwwGVeASS4AVdWAB0P%2BrS6YAKqMbgD6NgDygW60DgC6IAC%2BQA%3D):
* Balances for Ethereum, Solana, Arbitrum, Base, BSC, Optimism, Fantom, Polygon, Avalanche, Celo, Moonbeam, Scroll, Mantle, Blast, X Layer, World Chain, Sui and Aptos are displayed correctly. 
* Kaia - KLAY option is greyed out. Wrapped tokens are not displayed on wormhole-connect because of free RPC endpoint on Netlify deployments. Tokens are successfully loaded on Portal Bridge. Please see ticket https://github.com/wormhole-foundation/wormhole-connect/issues/2834.
