### ISSUE TITLE
[QA] Asset list in "To" section is incomplete on deploy-preview-2985

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#3150]
## Describe the current behavior in detail
Reproducible on [Netlify preview-2985](https://deploy-preview-2985--wormhole-connect-mainnet.netlify.app/?config=N4KABGDGD2CWB2BxAppA1tAggB1gaWQE8AuMAcgGFEBaAUQBEAZAMwBdGBDAMVoHUBNAI4AtAHIBnAAoA1AO4AhepjwVaZADTgwAJ2gBXVsnGkA2gFkOhDvABK%2BwwGVeASS4AVdWAB0P%2BrS6YAKqMbgD6NgDygW60DgC6IAC%2BQA%3D).
Balances are displayed correctly on https://wormhole-connect-mainnet.netlify.app/.

Steps:
1. Select Sui as target chain (Sui wallet auto-connects)
2. Check Assets list

Actual result: Assets list is empty. 
Expected result: SUI and USDC tokens are listed. 

## Notes/ Attachments

![Screenshot 2025-01-06 at 16 33 35](https://github.com/user-attachments/assets/9f4ed0f6-5307-4ed1-9ec4-9d1de1ae99a0)

**Comment by tsadovska** [comment]
Issue is also reproducible for Ethereum, Arbitrum, Base. 
Only ETH token is displayed in "To" section on [deploy-preview-2985](https://deploy-preview-2985--wormhole-connect-mainnet.netlify.app/?config=N4KAxg9glgdg4gUzAawgQQA5QNIIJ4BcABAOQDCcAtAKIAiAMgGYAu9AhgGLUDqAmgI4AtAHIBnAAoA1AO4AhWmmxlqJADQgiRGAmbSIAJ2TESAWzaxtzNRqIBXKMWCbRACwjSAkjHH6IAc30EUVFuKAATPx1iZn1bBCIAX3VNX1tmIOIAbRtNADp82moONABVegAVAH0AJQB5EvLqAGVkzSIAWTY8NhhqiDSEVQ6unr6B9rJy8SHO7t7%2B9KbuDw5y1rz8mGZmMfTRAApQNrbmCGQEGFFHHOOiYuFy2vbKkqbaMiyb26Ij79uwFzmGDGajMFwIQK2EzWP63MwwNiRfTGAAMAA8ELIwmQEABONi4gCMAGYwriACwolHUagAdgArAhGMTCTiABwAIzCxPJ5IAbAAmWgowlsQlgQkw2EnM4XVFotAojlsvm4olgQWEznEvkSsKE3G0clsAV46gclFgag6lF8zHktlS6VEGI9URgBBQABuEM%2BzuOv39bTYYTCgWC8vp9MYtLZApRxPptOKhNpaEJ1DIHId1Fx9MN9OofOJtI5HA4eb5YT5HCdQZdeAwCGMen0JjcABsEHXnUkvn8ALrrP5952B6UAoHGDg9U7Q4ew%2BGI32kdF8tlhWQCxgo%2BloE1hWm0wqMXFswmMMICjkIYkCvl8kmUsC4gVvjiyHt%2FU7nYGrtEChwtLEsSKJ5rIbIooq5IcsSnIorQhKWmQbJsuS9ICsapJgcqOpsF%2B3yupcHreiu2T1j8%2FbOiGYZBFc%2F6cuStI7qatIIPGqbkmAtJ8mwp5ISGYAoiGbJsDBCbktuXEEdKzCNs2pCtu2EBdjJ3yjv6Q5UW0GnfFpsL0OEECVNIojMNQ5QABJ%2BtK46wpOsAgmCEIIFCaltEuSLyhyFKibicECrS1aiXGHB8vSJJoPqsa4ny5K0GJbLMex8i4u5mg%2FnK%2F7McSuJkPS54cPm9KyPSxJgPSYAcgaHLCrBjAbmgur%2BYWApkGwKLpS6%2BhuiRPrIkQ5H1nZ%2Fo0eG9EkOi6ZoGQZCEggdphGwW6FQgXJEtaEX0mBxIcIShSFQKlWdQu%2FpyU2LYGMpqmnbCunSvp0r3d8I3fA5f4kLI7pdZ5K6TWiqqFfSmqqqysiMNatBhLQGHkmEdJITxHK0riHBQSigWOrdtyZR96L3hVCAirDV5FgKkFoA6HAChVKKMGFtAIGxGG5o%2BrJdUR7qev1NlBq90pjXR3m3kBRPrrSArUCiYRhWQtDJhwiayLSbBibI1W8ny7xqiqXXHOdCkkEpnbdtj6lm20j13djVu3NwvN%2FPzxzvcYTQqT0%2BEW5ov0DSQDzMPuEC0AAUi45yWQgbCSCUlkwHgLjSBy4jCGgwh8twfiyBglnIJZsjlBqh5evQ2Ac7KH1svSkiyBwACKghkLi5SCMgjBsBgzCyNwABWXolNItK8Bygjd3gGFNSY3fMOIcDd2ZtdoCYtccz1xHc2R2kvZvfyCxGpD%2B4HIdhwgEdRzHccJ0nKdpxnWc53nBdVrSxel17OPyZdbYm3riRv7bsL8FsBAdIvthD8GrAADX4GgNk9AOSiDILYOAbJ2j0G4NwWw4gVT0mEJIPk3dqiEnaByCBCBsBoiNJZEuId3LPVuE7NoLtSCgnBJCec29vYey8v%2BISEtZCEjQNQZkOoEBQwQPmaCsU1RCPJAgNkM4CwUkpljDhLpy7ylkHTGckEqSoTtEmDgKpQwYTij5Aq14BRRSShya8RIV69XXgNIafNVHHF3hNdEtAORRnJK%2BQ8BoEKEg5GwagbIZocilrlQkrJyTWjpJJcWlof4ZQ%2FopK63836aDoXpC22S2gMM0EwkgaB9AcigDENyb8faRhAthNAYAmrGnQlBUMNYEBAS1lrEkDIgL3jILIB05Iy6%2Fg0VotgOiUR6PEcmIxYQTEwTzHGGxVjSy2MlG%2FTmfUN4UQKbcdx8pELjLQLIVURMMYPjkcrIkYoSpkCYhFckhIypoG2uhNgfJkkNgumkr%2BKlTauN%2Fqo%2F%2Btw8maF2UU2oHcoAmCgKIdhQZqn%2FlFOSPabAUZ0wFLtRgPkjwClirqE5isqxkGrAVBMxIEAkmGVlf6mj6bjKpJMlU0zDFVjmfeBZ5jllhGsWs%2Bxa9SJOIBbstxoZxrylxLVTkpYMK0jIJTBawE2RgHkMtGWEUyBvn5HyBkfIUTATCJ8g2n9rr%2FIoqCy2uSLbgsBI5Ugsg2CiDNf6RF%2F0yogTCFBBpcUxLbSitWDg7SeK0C6SWekvS%2BT9MGdSvGaI6XaMZVMgxsz5lmKWZYnlqyfLrNUZsxxDsxwAs0Ps%2F8hywknNxGc%2B8do2RXNFE82QdyGSEkec8159J3lGtSUbdJfyf4Ws0MC44eTgX3QSAASlaI9WwTrqgIDCEEKAfg%2FwVMGDYXGCCIAwEYEu64xxTLmSsvAsAe7bjnEIIpMyFlLLHq%2FKIPAJgOQqRbFeqyX4ETMFImQW1H0vpgC%2FLjDwYRT1vR%2FcYP9MkS3%2FQJoyYmmFSaCgplTGm216ZayZuIyWsVolkC%2FHQqAkAPouG2BgK4AB6MjjqnXMFELkSAsBIgoAgHRiAJgyP0cuGR6Fy5RBka1GyHkZGzI9CWvoMIZGD3XtyBgGAfgvwccQExoDLYeoYCbGESgZkdAuHkypAwxgADExI0BoF2rWU6C6wDcY7PRLUw57rcFEO7BEIG2jnuMI55znt%2Bz3sfc%2B0g3B31sE%2FT6b9U5SBuw7B7AD5dlOUXsmBiLXnINiqFqQSu1c64Nybi3NuHcu6937oPYeo9x58kntPWe89F7L1OvhwjxhiPMFIwQCjVGdC0Y44x1ALG2Mcd49xyIvHEyTNpEJ5gIm2BiYk6x%2FQJtKgdn8MZRgtgOwdkqJARb%2BhKj6D8BySo8YqQYDRJUCWamoCVGxTxXiYBK5sGk7JgA%2FKmSZ642R5iGadBTSBUBxZ7b8m6%2FZLPWfonyezw5uDaZclCVzmh3MBah2wu9D6n0dg80FkLCAwt2pICw6H8KcaxeA%2FFv4RS8dI%2BxlB9E8aGW6OZcmtlqbFkWJWTY7NeHToEa3Y1kj5HKPBA6yxhjP3mOQD69ATjg2ghkZG0lcbk3pt6BMHNv5C2luXdW%2BtzbBgdt7YO4y47p2BTncu8jB8bBbsdoe34Z7tJXuoQ%2B7p2AinfvE%2F%2B6ar8wOzA2eIHZm4DmptlIqSYWHRB4ckG4IH8psQCfHF86j9Hp0P1fsS8U0p0fKn9kA8T%2FmRSSlB5jyl2ie9aVjImUmmZjOOVppZ5mtndi6uc4a6QJrLW2sC5o0L2TIvevsYlwNswQ2ZfbTl8JmAonxNK5V12NXfhlua423p7bu39uHZRIbs7WBTfXYt3d63tv7fvfpJ9%2Fs32lNu%2BNn2izSAQe%2B7ZODm43AIBQphXC0P4en8v9hbHto8f%2FMR4xxT3CxIEhU%2FVfx%2FwyiJ1D0KVT1AOhW%2FyL3FX%2FBp3L3p0r2MWr2Z25V5XZ0b37C5yI151a352o06wl261F1Yz71gAHx42H1G3l3Hym0n1m3m0Wznw1zW0Xy2111XwNxO03wuyu3N0t3uxkxtxexVAd2Pyd3gBFz%2B0v0B2%2BC9zYB9yID92HQh2CSdXf3wA820OdTjxR3%2F0CyT2CyAJxwdSdRi1%2FDi1z1TysMML2VSxL2pzL0TTQNZQwNMSwIzRwIb37Hq25xbyIPb1IK7woN736y40H2l1lzGzHwnxm2VzYPVxWy4O12Xz1zXw32Ny32EJuz33EIPykKPxPzeglxdwgAUN7SUNuBULUI0J0laD7ASAAG4QAgA%3D%3D). 



https://github.com/user-attachments/assets/7a0be365-7ffc-4dc5-ae04-4dbb60a1d6bb

**Comment by artursapek** [comment]
this should be fixed in that deploy preview

**Comment by tsadovska** [comment]
Rechecked the issue on [Netlify (preview 2985)](https://deploy-preview-2985--wormhole-connect-mainnet.netlify.app/?config=N4KABGDGD2CWB2BxAppA1tAggB1gaWQE8AuMAcgGFEBaAUQBEAZAMwBdGBDAMVoHUBNAI4AtAHIBnAAoA1AO4AhepjwVaZADTgwAJ2gBXVsnGkA2gFkOhDvABK%2BwwGVeASS4AVdWAB0P%2BrS6YAKqMbgD6NgDygW60DgC6IAC%2BQA%3D), issue still occurs.

* Ethereum, Solana, Arbitrum, Base, BSC, Optimism, Fantom, Polygon, Avalanche, Celo, Moonbeam, Kaia, Scroll, Mantle, Blast, X Layer, World Chain - only native tokens are displayed

![Screenshot 2025-01-08 at 13 10 00](https://github.com/user-attachments/assets/19869dab-289b-478d-9b06-119467a29ae7)

![image](https://github.com/user-attachments/assets/dfc1e6f3-d98d-41d7-8e95-d4b22a56fe47)

* Sui, Aptos - no supported tokens found

![image](https://github.com/user-attachments/assets/2f7408ed-6775-4969-97a9-e73a60f9c540)


![image](https://github.com/user-attachments/assets/a7afc372-399e-4fc8-892c-4387a8187b08)

**Comment by tsadovska** [comment]
Rechecked the issue on [Netlify (preview 2985)](https://deploy-preview-2985--wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBZAhgS2tSAXJANOGAMYD2WA4pCQNZkCCADhgNKQCeiSAwpQLQBRACIAZAGa5RaAGKCA6gE0AjgC0AcgGcACgDUA7gCFhDVj0GFiAJzIBXXJE2IA2gDp30XLgBKdh5oAKUAhcMloYJzBQYghYuLAZBnUAFQB5FAB9AFUAZWEeFxj44uDisogSAAtMaEQAIhk0TzIAWzqicvKWprQAc0greoAGAA8ANgAOABNDACZxIYBWBjRZqYB2deFBcQBOCYBGcSnZgCNIAGZZsbGDi4AWIZJd2deZQ3aiztjQ8NqwOqjWYydYXC5DXaLQwTIYMIb3U4XCanIbCA5PHgTCb3Raze5oC5TCGnCYXMZoT7fYq4KxNTQkSAYWADQpUsqlNnFNBTKZWRyRQEjZH3dYLWaCdaCWZDA7re48dZjBh7dHckiwqYTBj3QxDB7ze4kSmc6kcJiQer6MhWFqVMgAG0gxpNEAAvh0XQBdD1s91fToczlVGr1QS4SoDSC2No%2BzndaB9FkA0aQQxTHiQXZoXZ3Ka7R5DQQSxaQcQXA4Z5FTB73MazYQytAHEgHZ2c34wYYjOEksa7HMkOsHZFkltTA67YT42aZwQokiCMlDMap%2B4TNtsml0hlMpPOf1swMusDc3n8ruLRbidYTaUXRbrRKyhgHQQ8U5rwSQyeLQRjC7rKcMgyJCYxTGMMgbi6uBmhaAJWjadqOlBvqxmy3oHmUfroR6rogK6ACUBBgOgHBNL49iQDk8gAJIyMkxGkeRfiQMR7iuNsiRZKIyQZN4qRZMkgg5BhEBWEwJCRIGzChJESCVF4TBOAA9Mp4kkK4TS0FYrjkC0ylMHyLQYNG%2FAKbgTDKWgTCycpUyQLe%2FYPpsFynCi4jZpAQxoGgkBoKcD55li6xDOskBjEMkAouSlxjOcy6LMimwwusaz5rs6y7FMymwAclgQDktgYNw5lKfAqnqa43RYDguCuJoRWuBgZDKUgYDEHhrpAA), issue still occurs. 

Only native tokens are displayed on Ethereum, Solana, Arbitrum, Base, BSC, Optimism, Fantom, Polygon, Avalanche, Celo, Moonbeam, Kaia, Scroll, Mantle, Blast, X Layer, World Chain and Sui.


![Screenshot 2025-01-13 at 13 07 35](https://github.com/user-attachments/assets/c360ca25-1c0c-4c8d-9bae-125f7cb247a4)

![Screenshot 2025-01-13 at 13 08 31](https://github.com/user-attachments/assets/6c9c81a2-f77c-44a1-bb0b-faef481bb42a)

**Comment by tsadovska** [comment]
Rechecked on Jan 14, issue is still relevant. More tokens are displayed on https://wormhole-connect-mainnet.netlify.app/ compared to [Netlify (preview 2985)](https://deploy-preview-2985--wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBZAhgS2tSAXJANOGAMYD2WA4pCQNZkCCADhgNKQCeiSAwpQLQBRACIAZAGa5RaAGKCA6gE0AjgC0AcgGcACgDUA7gCFhDVj0GFiAJzIBXXJE2IA2gDp30XLgBKdh5oAKUAhcMloYJzBQYghYuLAZBnUAFQB5FAB9AFUAZWEeFxj44uDisogSAAtMaEQAIhk0TzIAWzqicvKWprQAc0greoAGAA8ANgAOABNDACZxIYBWBjRZqYB2deFBcQBOCYBGcSnZgCNIAGZZsbGDi4AWIZJd2deZQ3aiztjQ8NqwOqjWYydYXC5DXaLQwTIYMIb3U4XCanIbCA5PHgTCb3Raze5oC5TCGnCYXMZoT7fYq4KxNTQkSAYWADQpUsqlNnFNBTKZWRyRQEjZH3dYLWaCdaCWZDA7re48dZjBh7dHckiwqYTBj3QxDB7ze4kSmc6kcJiQer6MhWFqVMgAG0gxpNEAAvh0XQBdD1s91fToczlVGr1QS4SoDSC2No%2BzndaB9FkA0aQQxTHiQXZoXZ3Ka7R5DQQSxaQcQXA4Z5FTB73MazYQytAHEgHZ2c34wYYjOEksa7HMkOsHZFkltTA67YT42aZwQokiCMlDMap%2B4TNtsml0hlMpPOf1swMusDc3n8ruLRbidYTaUXRbrRKyhgHQQ8U5rwSQyeLQRjC7rKcMgyJCYxTGMMgbi6uBmhaAJWjadqOlBvqxmy3oHmUfroR6rogK6ACUBBgOgHBNL49iQDk8gAJIyMkxHuK42yJFkojJBk3ipFkySCDkGEQFYTAkJEgbMKEkRIJUXhME4AD0clCSQrhNLQViuOQLRyUwfItBg0b8NJuBMHJaBMBJclTJAt79g%2BmwXKcKLiNmkBDGgaCQGgpwPnmWLrEM6yQGMQyQCi5KXGM5zLosyKbDC6xrPmuzrLsUxybAByWBAOS2Bg3BGbJ8AKUprjdFgOC4K4mi5a4GBkHJSBgMQeGukAA) when user selects network in "To" section. 

https://github.com/user-attachments/assets/8f8f28d6-e18c-4353-a63a-fa25bacfa15f

**Comment by artursapek** [comment]
I think this depends on your Connect config, and if it has Mayan route in it.

**Comment by artursapek** [comment]
Fixed in https://github.com/wormhole-foundation/wormhole-connect/pull/2985/commits/56d42daa3ada65492bde0156fc6d890dfb974f24

**Comment by agodlevska** [comment]
Rechecked on [deploy-preview-2985](https://deploy-preview-2985--wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBZAhgS2tSAXJANOGAMYD2WA4pCQNZkCCADhgNKQCeiSAwpQLQBRACIAZAGa5RaAGKCA6gE0AjgC0AcgGcACgDUA7gCFhDVj0GFiAJzIBXXJE2IA2gDp30XLgBKdh5oAKUAhcMloYJzBQYghYuLAZBnUAFQB5FAB9AFUAZWEeFxj44uDisogSAAtMaEQAIhk0TzIAWzqicvKWprQAc0greoAGAA8ANgAOABNDACZxIYBWBjRZqYB2deFBcQBOCYBGcSnZgCNIAGZZsbGDi4AWIZJd2deZQ3aiztjQ8NqwOqjWYydYXC5DXaLQwTIYMIb3U4XCanIbCA5PHgTCb3Raze5oC5TCGnCYXMZoT7fYq4KxNTQkSAYWADQpUsqlNnFNBTKZWRyRQEjZH3dYLWaCdaCWZDA7re48dZjBh7dHckiwqYTBj3QxDB7ze4kSmc6kcJiQer6MhWFqVMgAG0gxpNEAAvh0XQBdD1s91fToczlVGr1QS4SoDSC2No%2BzndaB9FkA0aQQxTHiQXZoXZ3Ka7R5DQQSxaQcQXA4Z5FTB73MazYQytAHEgHZ2c34wYYjOEksa7HMkOsHZFkltTA67YT42aZwQokiCMlDMap%2B4TNtsml0hlMpPOf1swMusDc3n8ruLRbidYTaUXRbrRKyhgHQQ8U5rwSQyeLQRjC7rKcMgyJCYxTGMMgbi6uBmhaAJWjadqOlBvqxmy3oHmUfroR6rogK6ACUBBgOgHBNL49iQDk8gAJIyMkxHuK42yJFkojJBk3ipFkySCDkGEQFYTAkJEgbMKEkRIJUXhME4AD0clCSQrhNLQViuOQLRyUwfItBg0b8NJuBMHJaBMBJclTJAt79g%2BmwXKcKLiNmkBDGgaCQGgpwPnmWLrEM6yQGMQyQCi5KXGM5zLosyKbDC6xrPmuzrLsUxybAByWBAOS2Bg3BGbJ8AKUprjdFgOC4K4mi5a4GBkHJSBgMQeGukAA).
-  Issue is no longer reproducible, for Ethereum, Solana, Arbitrum, Base, BSC, Optimism, Fantom, Polygon, Avalanche, Celo, Moonbeam, Scroll, Mantle, Blast, X Layer, World Chain, Sui are displayed correctly.

https://github.com/user-attachments/assets/8b4cd05e-fcf3-4bbb-9730-9170e25269db


- Aptos - APT option is greyed out on the source chain, balance is not loading in "To" section . Please see ticket https://github.com/wormhole-foundation/wormhole-connect/issues/3156.
- Kaia - KLAY option is greyed out on the source chain, KLAY and WKLAY balance is not loading in "To" section, error in console:
```
Failed to get token balances Error: could not coalesce error (error={ "code": -32062, "data": { "trace_id": "e5cd58f47f41c5ae07081c8fc13ae96c" }, "message": "Batch size too large" }, payload={ "id": 2, "jsonrpc": "2.0", "method": "eth_getBalance", "params": [ "0xd493066498ace409059fda4c1bcd2e73d8cffe01", "latest" ] }, code=UNKNOWN_ERROR, version=6.13.5)
    at makeError (main-u58l_hBg.js:289:68378)
    at Hl.getRpcError (main-u58l_hBg.js:290:214433)
    at main-u58l_hBg.js:290:216735
``` 
<img width="1440" alt="Screenshot 2025-01-15 at 16 17 08" src="https://github.com/user-attachments/assets/9423aabe-96bb-4f61-b23c-964b2d3fc621" />

wormhole-connect-mainnet:

<img width="588" alt="Screenshot 2025-01-15 at 16 16 55" src="https://github.com/user-attachments/assets/278e5701-50be-4c13-a80e-dea27a846037" />

**Comment by tsadovska** [comment]
Issue is no longer reproducible. Checked on https://portalbridge.com/. 

https://github.com/user-attachments/assets/0527de44-ec24-43c3-8670-b88ef91d71e3
